version: '3.10'

services:
  db:
    image: postgres:latest
    ports:
      - 6321:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
  threadhub:
    build: .
    command: /bin/bash threadhub/start.sh
    volumes:
      - .:/threadhub
    ports:
      - 8000:8000
    depends_on:
      - db
  migration:
    build: .
    image: db
    command: python threadhub/manage.py makemigrations
    volumes:
      - .:/threadhub
    links:
      - db
    depends_on:
      - db

volumes:
  postgres-db-data: